### ISSUE TITLE
Zeroizing conversion reordering

### ISSUE THREAD

**Issue by ionut-arm** [iqlusioninc/crates#453]
Hi,

We've been working on integrating the `zeroize` crate into our libraries but we ended up with a question to which you might or might not have an answer:

We have some code that overall looks like this:
```rust
let x = something.into();
let y = SomeType {
  bla: blabla.try_into()?,
  x
};
```

The question is - could the compiler optimize that `into()` to be after the `try_into()?`, thus potentially not performing the `into` conversion? The idea is that `x` ends up being of type `Zeroizing<T>` and thus cleans up the contents when being dropped, but if the conversion doesn't happen the other type doesn't clean up and is then dropped as is.

**Comment by tony-iqlusion** [comment]
Apologies for the belated reply.

The `zeroize` crate uses a [compiler fence with `Ordering::SeqCst`](https://github.com/iqlusioninc/crates/blob/c8ddb00/zeroize/src/lib.rs#L474-L480) in order to signal to the compiler that such reordering shouldn't be performed.

This fence occurs right after the (volatile in the Rust/LLVM sense) bzero/memset-like operation. It's a similar approach to the one used in the implementation of various libc functions for securely zeroing memory like `memset_s`.

When we reviewed this usage with the [Unsafe Code Guidelines Working Group](https://github.com/rust-lang/unsafe-code-guidelines) it was deemed sufficient for our purposes. However, if you do notice any such reordering in generated assembly, please let us know.
