### ISSUE TITLE
`hkd32::Error` does not implement `std::error::Error`

### ISSUE THREAD

**Issue by thomaseizinger** [iqlusioninc/crates#841]
Is this intentional? It makes it unergonomic to use together with crates like `anyhow`.

Happy to send a patch if we can agree on what `fmt::Display` should return for this error.

**Comment by tony-iqlusion** [comment]
It isn't "intentional", it's just there's a somewhat onerous amount of boilerplate to implement it for a `no_std` friendly crate.

You can read the instructions I gave for it on another crate I received this same request for today if you'd like to submit a PR:

https://github.com/RustCrypto/password-hashes/issues/199
